#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
	CREATE DATABASE "$DB_NAME";

    CREATE ROLE liquibase WITH LOGIN PASSWORD '$DB_LIQUIBASE_PASSWORD';
    GRANT CONNECT ON DATABASE "$DB_NAME" TO liquibase;

    CREATE ROLE app WITH LOGIN PASSWORD '$DB_APP_PASSWORD';
    GRANT CONNECT ON DATABASE "$DB_NAME" TO app;


    -- connect to WOC database
    \c "$DB_NAME";

    CREATE SCHEMA woc;

    GRANT USAGE ON SCHEMA woc TO liquibase;
    GRANT CREATE ON SCHEMA woc TO liquibase;
    ALTER DEFAULT PRIVILEGES IN SCHEMA woc GRANT ALL PRIVILEGES ON TABLES TO liquibase;

    GRANT USAGE ON SCHEMA woc TO app;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA woc TO app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA woc GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app;
EOSQL
