spring.application.name=workoutoclock

woc.security.jwt.secret-key=${API_JWT_SECRET_KEY}
woc.security.jwt.duration=900
woc.security.jwt.refresh-duration=604800

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.default_schema=woc 
spring.datasource.url=jdbc:postgresql://${API_DB_HOST}:5432/${DB_NAME}
spring.datasource.username=app
spring.datasource.password=${DB_APP_PASSWORD}


spring.devtools.restart.log-condition-evaluation-delta=false
spring.jpa.hibernate.ddl-auto=validate

# expose only explicitly declared endpoints
spring.data.rest.detection-strategy=annotated

# enabled only with dev profile
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false