@startuml woc

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>


table(user) {
    primary_key(user_id): BIGINT NOT NULL
    --
    column(username): VARCHAR(255) NOT NULL
    column(email): VARCHAR(255) NOT NULL
    column(password): VARCHAR(MAX) NOT NULL
    column(created_date): DATETIME NOT NULL
    column(modified_date): DATETIME
}

table(workout_set) {
    primary_key(set_id): BIGINT NOT NULL
    --
    foreign_key(user_id): BIGINT NOT NULL
    column(title): VARCHAR(64)
    column(card_color_hex): VARCHAR(8)
}

table(workout_task) {
    primary_key(task_id): BIGINT
    --
    foreign_key(set_id): BIGINT NOT NULL
    column(index): INT
    column(title): VARCHAR(64)
    column(objective_type): CHAR(1)
    column(objective_reps): INT
    column(objective_time_secs): INT
    column(card_color_hex): VARCHAR(8)
}
note right: objective_type as "R" for reps or "T" for time in seconds

table(refresh_token) {
    primary_key(token_id): BIGINT
    --
    foreign_key(user_id): BIGINT NOT NULL
    column(issued_date): DATETIME NOT NULL
    column(expired_date): DATETIME
    column(token_string): TEXT UNIQUE
    column(valid): BOOLEAN DEFAULT TRUE
}


workout_set }o-up-|| user
workout_task }o-up-|| workout_set
refresh_token }o-left-|| user

@enduml